const PHONETICS = {
  "(real) estate agent": "/ɪstˈeɪt ˈeɪdʒʌnt/",
  "a chest of drawers": "/ʌ tʃˈɛst ˈʌv drˈɔrz/",
  "a chorus of": "/ʌ kˈɔrʌs ˈʌv/",
  "a flock of": "/ʌ flˈɑk ˈʌv/",
  "a handful of": "/ʌ hˈændfˌʊl ˈʌv/",
  "aborigine": "/ˌæbɝˈɪdʒʌni/",
  "absurd": "/ʌbsˈɝd/",
  "accountant": "/ʌkˈaʊntʌnt/",
  "accuse": "/ʌkjˈuz/",
  "acquire": "/ʌkwˈaɪɝ/",
  "alien": "/ˈeɪliʌn/",
  "applaud": "/ʌplˈɔd/",
  "appointment": "/ʌpˈɔɪntmʌnt/",
  "aptitude": "/ˈæptʌtˌud/",
  "arrest": "/ɝˈɛst/",
  "arrow": "/ˈæroʊ/",
  "assemble": "/ʌsˈɛmbʌl/",
  "attend to": "/ʌtˈɛnd tˈu/",
  "backwards (name backward)": "/bˈækwɝdz/",
  "bakery": "/bˈeɪkɝi/",
  "barbecue (abbr. bbq)": "/bˈɑrbɪkjˌu/",
  "behold": "/bɪhˈoʊld/",
  "biology": "/baɪˈɑlʌdʒi/",
  "blurred": "/blˈɝd/",
  "bond": "/bˈɑnd/",
  "bondi beach": "/bˈɑndi bˈitʃ/",
  "bonus": "/bˈoʊnʌs/",
  "bounce": "/bˈaʊns/",
  "bounce around": "/bˈaʊns ɝˈaʊnd/",
  "braille (also braille)": "/brˈeɪl/",
  "breast": "/brˈɛst/",
  "bridegroom": "/brˈaɪdɡrˌum/",
  "bubble": "/bˈʌbʌl/",
  "bungee jumping": "/bˈʌndʒi dʒˈʌmpɪŋ/",
  "butcher": "/bˈʊtʃɝ/",
  "cage": "/kˈeɪdʒ/",
  "calculate": "/kˈælkjʌlˌeɪt/",
  "camel": "/kˈæmʌl/",
  "canal": "/kʌnˈæl/",
  "capacity": "/kʌpˈæsʌti/",
  "capsule": "/kˈæpsʌl/",
  "cardiac": "/kˈɑrdiˌæk/",
  "certificate": "/sɝtˈɪfɪkʌt/",
  "ceylon": "/sɪlˈɑn/",
  "chairwoman": "/tʃˈɛrwˌʊmʌn/",
  "channel": "/tʃˈænʌl/",
  "chemist": "/kˈɛmɪst/",
  "chiang mai": "/tʃˈæŋ mˈaɪ/",
  "chorus": "/kˈɔrʌs/",
  "churchill": "/tʃˈɝtʃɪl/",
  "circuit": "/sˈɝkʌt/",
  "circus": "/sˈɝkʌs/",
  "claire": "/klˈɛr/",
  "clay": "/klˈeɪ/",
  "code": "/kˈoʊd/",
  "collar": "/kˈɑlɝ/",
  "columbus": "/kʌlˈʌmbʌs/",
  "come to a conclusion": "/kˈʌm tˈu ʌ kʌnklˈuʒʌn/",
  "communist": "/kˈɑmjʌnʌst/",
  "conflict with": "/kˈɑnflɪkt wˈɪð/",
  "congo": "/kˈɑŋɡoʊ/",
  "consultation": "/kˌɑnsʌltˈeɪʃʌn/",
  "contract": "/kˈɑntrˌækt/",
  "coral": "/kˈɔrʌl/",
  "cotton": "/kˈɑtʌn/",
  "council": "/kˈaʊnsʌl/",
  "coverage": "/kˈʌvɝʌdʒ/",
  "criterion": "/kraɪtˈɪriʌn/",
  "cv (name résumé)": "/sˌivˈi/",
  "debt": "/dˈɛt/",
  "declare": "/dɪklˈɛr/",
  "dedicate": "/dˈɛdʌkˌeɪt/",
  "desert": "/dˈɛzɝt/",
  "deserve": "/dɪzˈɝv/",
  "detective": "/dɪtˈɛktɪv/",
  "dignity": "/dˈɪɡnʌti/",
  "dim sim": "/dˈɪm sˈɪm/",
  "directory": "/dɝˈɛktɝi/",
  "disability": "/dˌɪsʌbˈɪlɪti/",
  "disabled": "/dɪsˈeɪbʌld/",
  "disk (disc)": "/dˈɪsk/",
  "dismiss": "/dɪsmˈɪs/",
  "distribution": "/dˌɪstrʌbjˈuʃʌn/",
  "dive": "/dˈaɪv/",
  "division": "/dɪvˈɪʒʌn/",
  "domain": "/doʊmˈeɪn/",
  "doorway": "/dˈɔrwˌeɪ/",
  "drag": "/drˈæɡ/",
  "drawer": "/drˈɔr/",
  "duck-billed platypus": "/dˈʌk bˈɪld plˈætʌpˌʊs/",
  "dust": "/dˈʌst/",
  "dusty": "/dˈʌsti/",
  "edmonds": "/ˈɛdmʌndz/",
  "employer": "/ɛmplˈɔɪɝ/",
  "entitle": "/ɛntˈaɪtʌl/",
  "entrepreneur": "/ˌɑntrʌprʌnˈɝ/",
  "equator": "/ɪkwˈeɪtɝ/",
  "estate": "/ɪstˈeɪt/",
  "explode": "/ɪksplˈoʊd/",
  "exploit": "/ˈɛksplˌɔɪt/",
  "extend": "/ɪkstˈɛnd/",
  "fall away": "/fˈɔl ʌwˈeɪ/",
  "fare": "/fˈɛr/",
  "felicity": "/fɪlˈɪsʌti/",
  "fence": "/fˈɛns/",
  "ferdinand magellan": "/fˈɝdɪnˌænd mʌdʒˈɛlʌn/",
  "fetch": "/fˈɛtʃ/",
  "fiction": "/fˈɪkʃʌn/",
  "finance": "/fʌnˈæns/",
  "fireplace": "/fˈaɪɝplˌeɪs/",
  "flea collar": "/flˈi kˈɑlɝ/",
  "fleet": "/flˈit/",
  "flip": "/flˈɪp/",
  "flour": "/flˈaʊɝ/",
  "forehead": "/fˈɔrhɛd/",
  "foundation": "/faʊndˈeɪʃʌn/",
  "fox": "/fˈɑks/",
  "freedom": "/frˈidʌm/",
  "frequency": "/frˈikwʌnsi/",
  "frog": "/frˈɑɡ/",
  "fry": "/frˈaɪ/",
  "gallon": "/ɡˈælʌn/",
  "geometry": "/dʒiˈɑmʌtri/",
  "geothermal park": "/dʒˌioʊθˈɝmʌl pˈɑrk/",
  "getaway": "/ɡˈɛtʌwˌeɪ/",
  "geyser": "/ɡˈaɪzɝ/",
  "ghana": "/ɡˈænʌ/",
  "gladys claffern": "/ɡlˈædɪs/",
  "golf": "/ɡˈɑlf/",
  "grand": "/ɡrˈænd/",
  "grant": "/ɡrˈænt/",
  "graphic": "/ɡrˈæfɪk/",
  "greedy": "/ɡrˈidi/",
  "grill": "/ɡrˈɪl/",
  "grip": "/ɡrˈɪp/",
  "guilty": "/ɡˈɪlti/",
  "handkerchief": "/hˈæŋkɝtʃɪf/",
  "handshake": "/hˈændʃˌeɪk/",
  "handwriting": "/hˈændrˌaɪtɪŋ/",
  "hatch": "/hˈætʃ/",
  "have an urge to": "/hˈæv ˈæn ˈɝdʒ tˈu/",
  "hazy": "/hˈeɪzi/",
  "head start": "/hˈɛd stˈɑrt/",
  "herb": "/ˈɝb/",
  "hollow": "/hˈɑloʊ/",
  "horn": "/hˈɔrn/",
  "housing": "/hˈaʊzɪŋ/",
  "hugo award": "/hjˈuɡoʊ əˈwɔrd/",
  "hut": "/hˈʌt/",
  "hydrogen": "/hˈaɪdrʌdʒʌn/",
  "hypothetical": "/hˌaɪpʌθˈɛtʌkʌl/",
  "iconic": "/ˌaɪkˈɑnɪk/",
  "in a league of one’s own": "/ɪn ʌ lˈiɡ ˈʌv wˈʌnz ˈoʊn/",
  "in hand": "/ɪn hˈænd/",
  "inaction": "/ˌɪnˈækʃʌn/",
  "inch": "/ˈɪntʃ/",
  "input": "/ˈɪnpˌʊt/",
  "integrity": "/ˌɪntˈɛɡrʌti/",
  "intermediate": "/ˌɪntɝmˈidiɪt/",
  "isaac asimov": "/ˈaɪzʌk ˈæsɪmɑv/",
  "jam": "/dʒˈæm/",
  "jar": "/dʒˈɑr/",
  "jaw": "/dʒˈɔ/",
  "joint": "/dʒˈɔɪnt/",
  "jolt": "/dʒˈoʊlt/",
  "justice": "/dʒˈʌstʌs/",
  "kayaking": "/kˈaɪˌækɪŋ/",
  "kettle": "/kˈɛtʌl/",
  "kiwi": "/kˈiwi/",
  "knit": "/nˈɪt/",
  "labour": "/lˈeɪbɝ/",
  "ladder": "/lˈædɝ/",
  "lamp": "/lˈæmp/",
  "laptop": "/lˈæptˌɑp/",
  "larry belmont": "/lˈɛri bˈɛlmˌɑnt/",
  "lately": "/lˈeɪtli/",
  "lawyer": "/lˈɔjɝ/",
  "league": "/lˈiɡ/",
  "leather": "/lˈɛðɝ/",
  "leftover": "/lˈɛftˌoʊvɝ/",
  "lever": "/lˈɛvɝ/",
  "liberty": "/lˈɪbɝtˌi/",
  "license": "/lˈaɪsʌns/",
  "licensed": "/lˈaɪsʌnst/",
  "located": "/lˈoʊkˌeɪtʌd/",
  "log": "/lˈɔɡ/",
  "mail": "/mˈeɪl/",
  "mammal": "/mˈæmʌl/",
  "manned": "/mˈænd/",
  "manuka honey": "/ˈhʌni/",
  "marco polo": "/mˈɑrkoʊ pˈoʊloʊ/",
  "marie curie": "/mɝˈi kjʊrˈi/",
  "marine": "/mɝˈin/",
  "maritime": "/mˈɛrʌtˌaɪm/",
  "maximum": "/mˈæksʌmʌm/",
  "meanwhile": "/mˈinwˌaɪl/",
  "merchant": "/mˈɝtʃʌnt/",
  "mercy": "/mˈɝsi/",
  "migration": "/maɪɡrˈeɪʃʌn/",
  "minister": "/mˈɪnʌstɝ/",
  "mixture": "/mˈɪkstʃɝ/",
  "monument": "/mˈɑnjumʌnt/",
  "more like": "/mˈɔr lˈaɪk/",
  "mud": "/mˈʌd/",
  "murder": "/mˈɝdɝ/",
  "nail": "/nˈeɪl/",
  "negotiate": "/nʌɡˈoʊʃiˌeɪt/",
  "nest": "/nˈɛst/",
  "niece": "/nˈis/",
  "not to mention": "/nˈɑt tˈu mˈɛnʃʌn/",
  "olivia": "/oʊlˈɪviʌ/",
  "on a … basis": "/ˈɑn ʌ ˈbeɪsəs/",
  "opponent": "/ʌpˈoʊnʌnt/",
  "orient": "/ˈɔriˌɛnt/",
  "overstatement": "/ˈoʊvɝstˌeɪtmʌnt/",
  "pace": "/pˈeɪs/",
  "pan": "/pˈæn/",
  "panama": "/pˈænʌmˌɑ/",
  "panel": "/pˈænʌl/",
  "papua new guinea": "/pˈæpjuʌ nˈu ɡˈɪni/",
  "parcel": "/pˈɑrsʌl/",
  "parking": "/pˈɑrkɪŋ/",
  "participant": "/pɑrtˈɪsʌpʌnt/",
  "peak season": "/pˈik sˈizʌn/",
  "pets (public english test system)": "/pˈɛts/",
  "phase": "/fˈeɪz/",
  "pitch": "/pˈɪtʃ/",
  "platform": "/plˈætfˌɔrm/",
  "plug": "/plˈʌɡ/",
  "political": "/pʌlˈɪtʌkʌl/",
  "politics": "/pˈɑlʌtˌɪks/",
  "possession": "/pʌzˈɛʃʌn/",
  "pouch": "/pˈaʊtʃ/",
  "pray": "/prˈeɪ/",
  "pray that": "/prˈeɪ ðˈæt/",
  "premier": "/prɛmˈɪr/",
  "press conference": "/ˈprɛs ˈkɑnfɚəns/",
  "presume": "/prɪzˈum/",
  "prime minister": "/prˈaɪm mˈɪnʌstɝ/",
  "priority": "/praɪˈɔrʌti/",
  "prison": "/prˈɪzʌn/",
  "privilege": "/prˈɪvlʌdʒ/",
  "profession": "/prʌfˈɛʃʌn/",
  "proficiency": "/prʌfˈɪʃʌnsi/",
  "profile": "/prˈoʊfˌaɪl/",
  "pros and cons": "/prˈoʊz ʌnd kˈɑnz/",
  "puff": "/pˈʌf/",
  "purse": "/pˈɝs/",
  "radium": "/rˈeɪdiʌm/",
  "random": "/rˈændʌm/",
  "receipt": "/rɪsˈit/",
  "receptionist": "/rɪsˈɛpʃʌnɪst/",
  "relay": "/rˈilˌeɪ/",
  "relay to": "/rˈilˌeɪ tˈu/",
  "resign": "/rɪzˈaɪn/",
  "ridiculous": "/rɪdˈɪkjʌlʌs/",
  "rigid": "/rˈɪdʒʌd/",
  "ripe": "/rˈaɪp/",
  "robin lee graham": "/rˈɑbʌn lˈi ɡrˈeɪʌm/",
  "royal": "/rˈɔɪʌl/",
  "rubber": "/rˈʌbɝ/",
  "rumour": "/rˈumɝ/",
  "salary": "/sˈælɝi/",
  "salesman": "/sˈeɪlzmʌn/",
  "saleswoman": "/sˈeɪlzwˌʊmʌn/",
  "sample": "/sˈæmpʌl/",
  "saucer": "/sˈɔsɝ/",
  "scenario": "/sɪnˈɛrioʊ/",
  "science fiction": "/sˈaɪʌns fˈɪkʃʌn/",
  "secondary": "/sˈɛkʌndˌɛri/",
  "session": "/sˈɛʃʌn/",
  "set sail": "/sˈɛt ˈseɪl/",
  "sew": "/sˈoʊ/",
  "shade": "/ʃˈeɪd/",
  "slogan": "/slˈoʊɡʌn/",
  "socialist": "/sˈoʊʃʌlʌst/",
  "spice": "/spˈaɪs/",
  "sponsor": "/spˈɑnsɝ/",
  "spy": "/spˈaɪ/",
  "stability": "/stʌbˈɪlɪti/",
  "straightforward": "/strˈeɪtfˈɔrwɝd/",
  "strait": "/strˈeɪt/",
  "stun": "/stˈʌn/",
  "submersible": "/sʌbmˈɝsɪbʌl/",
  "sulphuric pool": "/pˈul/",
  "superior": "/supˈɪriɝ/",
  "superior to": "/supˈɪriɝ tˈu/",
  "supervise": "/sˈupɝvˌaɪz/",
  "suspend": "/sʌspˈɛnd/",
  "sydney": "/sˈɪdni/",
  "tablet": "/tˈæblʌt/",
  "take (…) for granted": "/tˈeɪk fˈɔr ɡrˈæntʌd/",
  "take over": "/tˈeɪk ˈoʊvɝ/",
  "tale": "/tˈeɪl/",
  "tasmania": "/tˌæzmˈeɪniʌ/",
  "tasmanian devil": "/tˌæzmˈeɪniʌn dˈɛvʌl/",
  "tax": "/tˈæks/",
  "temporary": "/tˈɛmpɝˌɛri/",
  "test out": "/tˈɛst ˈaʊt/",
  "the bay of islands": "/ðʌ bˈeɪ ˈʌv ˈaɪlʌndz/",
  "the communist manifesto": "/ðʌ kˈɑmjʌnʌst mˌænʌfˈɛstˌoʊ/",
  "the haka": "/ðʌ/",
  "the three-body problem": "/ðʌ θrˈi bˈɑdi prˈɑblʌm/",
  "tournament": "/tˈʊrnʌmʌnt/",
  "trunk": "/trˈʌŋk/",
  "tube": "/tˈub/",
  "tune": "/tˈun/",
  "turn out": "/tˈɝn ˈaʊt/",
  "underwater": "/ˈʌndɝwˌɔtɝ/",
  "uniform": "/jˈunʌfˌɔrm/",
  "urge": "/ˈɝdʒ/",
  "venue": "/vˈɛnju/",
  "vibrate": "/vˈaɪbreɪt/",
  "violence": "/vˈaɪʌlʌns/",
  "violent": "/vˈaɪʌlʌnt/",
  "washroom": "/wˈɑʃrˌum/",
  "weed": "/wˈid/",
  "weekly": "/wˈikli/",
  "whereas": "/wɛrˈæz/",
  "withdraw": "/wɪðdrˈɔ/",
  "withdraw from": "/wɪðdrˈɔ frˈʌm/",
  "wool": "/wˈʊl/",
  "wrinkle": "/rˈɪŋkʌl/",
  "wrist": "/rˈɪst/",
  "zac sunderland": "/sˈʌndɝlʌnd/"
};
