const PHONETICS = {
  "(real) estate agent": "/瑟st藞e瑟t 藞e瑟d蕭蕦nt/",
  "a chest of drawers": "/蕦 t蕛藞蓻st 藞蕦v dr藞蓴rz/",
  "a chorus of": "/蕦 k藞蓴r蕦s 藞蕦v/",
  "a flock of": "/蕦 fl藞蓱k 藞蕦v/",
  "a handful of": "/蕦 h藞忙ndf藢蕣l 藞蕦v/",
  "aborigine": "/藢忙b蓾藞瑟d蕭蕦ni/",
  "absurd": "/蕦bs藞蓾d/",
  "accountant": "/蕦k藞a蕣nt蕦nt/",
  "accuse": "/蕦kj藞uz/",
  "acquire": "/蕦kw藞a瑟蓾/",
  "alien": "/藞e瑟li蕦n/",
  "applaud": "/蕦pl藞蓴d/",
  "appointment": "/蕦p藞蓴瑟ntm蕦nt/",
  "aptitude": "/藞忙pt蕦t藢ud/",
  "arrest": "/蓾藞蓻st/",
  "arrow": "/藞忙ro蕣/",
  "assemble": "/蕦s藞蓻mb蕦l/",
  "attend to": "/蕦t藞蓻nd t藞u/",
  "backwards (name backward)": "/b藞忙kw蓾dz/",
  "bakery": "/b藞e瑟k蓾i/",
  "barbecue (abbr. bbq)": "/b藞蓱rb瑟kj藢u/",
  "behold": "/b瑟h藞o蕣ld/",
  "biology": "/ba瑟藞蓱l蕦d蕭i/",
  "blurred": "/bl藞蓾d/",
  "bond": "/b藞蓱nd/",
  "bondi beach": "/b藞蓱ndi b藞it蕛/",
  "bonus": "/b藞o蕣n蕦s/",
  "bounce": "/b藞a蕣ns/",
  "bounce around": "/b藞a蕣ns 蓾藞a蕣nd/",
  "braille (also braille)": "/br藞e瑟l/",
  "breast": "/br藞蓻st/",
  "bridegroom": "/br藞a瑟d伞r藢um/",
  "bubble": "/b藞蕦b蕦l/",
  "bungee jumping": "/b藞蕦nd蕭i d蕭藞蕦mp瑟艐/",
  "butcher": "/b藞蕣t蕛蓾/",
  "cage": "/k藞e瑟d蕭/",
  "calculate": "/k藞忙lkj蕦l藢e瑟t/",
  "camel": "/k藞忙m蕦l/",
  "canal": "/k蕦n藞忙l/",
  "capacity": "/k蕦p藞忙s蕦ti/",
  "capsule": "/k藞忙ps蕦l/",
  "cardiac": "/k藞蓱rdi藢忙k/",
  "certificate": "/s蓾t藞瑟f瑟k蕦t/",
  "ceylon": "/s瑟l藞蓱n/",
  "chairwoman": "/t蕛藞蓻rw藢蕣m蕦n/",
  "channel": "/t蕛藞忙n蕦l/",
  "chemist": "/k藞蓻m瑟st/",
  "chiang mai": "/t蕛藞忙艐 m藞a瑟/",
  "chorus": "/k藞蓴r蕦s/",
  "churchill": "/t蕛藞蓾t蕛瑟l/",
  "circuit": "/s藞蓾k蕦t/",
  "circus": "/s藞蓾k蕦s/",
  "claire": "/kl藞蓻r/",
  "clay": "/kl藞e瑟/",
  "code": "/k藞o蕣d/",
  "collar": "/k藞蓱l蓾/",
  "columbus": "/k蕦l藞蕦mb蕦s/",
  "come to a conclusion": "/k藞蕦m t藞u 蕦 k蕦nkl藞u蕭蕦n/",
  "communist": "/k藞蓱mj蕦n蕦st/",
  "conflict with": "/k藞蓱nfl瑟kt w藞瑟冒/",
  "congo": "/k藞蓱艐伞o蕣/",
  "consultation": "/k藢蓱ns蕦lt藞e瑟蕛蕦n/",
  "contract": "/k藞蓱ntr藢忙kt/",
  "coral": "/k藞蓴r蕦l/",
  "cotton": "/k藞蓱t蕦n/",
  "council": "/k藞a蕣ns蕦l/",
  "coverage": "/k藞蕦v蓾蕦d蕭/",
  "criterion": "/kra瑟t藞瑟ri蕦n/",
  "cv (name r茅sum茅)": "/s藢iv藞i/",
  "debt": "/d藞蓻t/",
  "declare": "/d瑟kl藞蓻r/",
  "dedicate": "/d藞蓻d蕦k藢e瑟t/",
  "desert": "/d藞蓻z蓾t/",
  "deserve": "/d瑟z藞蓾v/",
  "detective": "/d瑟t藞蓻kt瑟v/",
  "dignity": "/d藞瑟伞n蕦ti/",
  "dim sim": "/d藞瑟m s藞瑟m/",
  "directory": "/d蓾藞蓻kt蓾i/",
  "disability": "/d藢瑟s蕦b藞瑟l瑟ti/",
  "disabled": "/d瑟s藞e瑟b蕦ld/",
  "disk (disc)": "/d藞瑟sk/",
  "dismiss": "/d瑟sm藞瑟s/",
  "distribution": "/d藢瑟str蕦bj藞u蕛蕦n/",
  "dive": "/d藞a瑟v/",
  "division": "/d瑟v藞瑟蕭蕦n/",
  "domain": "/do蕣m藞e瑟n/",
  "doorway": "/d藞蓴rw藢e瑟/",
  "drag": "/dr藞忙伞/",
  "drawer": "/dr藞蓴r/",
  "duck-billed platypus": "/d藞蕦k b藞瑟ld pl藞忙t蕦p藢蕣s/",
  "dust": "/d藞蕦st/",
  "dusty": "/d藞蕦sti/",
  "edmonds": "/藞蓻dm蕦ndz/",
  "employer": "/蓻mpl藞蓴瑟蓾/",
  "entitle": "/蓻nt藞a瑟t蕦l/",
  "entrepreneur": "/藢蓱ntr蕦pr蕦n藞蓾/",
  "equator": "/瑟kw藞e瑟t蓾/",
  "estate": "/瑟st藞e瑟t/",
  "explode": "/瑟kspl藞o蕣d/",
  "exploit": "/藞蓻kspl藢蓴瑟t/",
  "extend": "/瑟kst藞蓻nd/",
  "fall away": "/f藞蓴l 蕦w藞e瑟/",
  "fare": "/f藞蓻r/",
  "felicity": "/f瑟l藞瑟s蕦ti/",
  "fence": "/f藞蓻ns/",
  "ferdinand magellan": "/f藞蓾d瑟n藢忙nd m蕦d蕭藞蓻l蕦n/",
  "fetch": "/f藞蓻t蕛/",
  "fiction": "/f藞瑟k蕛蕦n/",
  "finance": "/f蕦n藞忙ns/",
  "fireplace": "/f藞a瑟蓾pl藢e瑟s/",
  "flea collar": "/fl藞i k藞蓱l蓾/",
  "fleet": "/fl藞it/",
  "flip": "/fl藞瑟p/",
  "flour": "/fl藞a蕣蓾/",
  "forehead": "/f藞蓴rh蓻d/",
  "foundation": "/fa蕣nd藞e瑟蕛蕦n/",
  "fox": "/f藞蓱ks/",
  "freedom": "/fr藞id蕦m/",
  "frequency": "/fr藞ikw蕦nsi/",
  "frog": "/fr藞蓱伞/",
  "fry": "/fr藞a瑟/",
  "gallon": "/伞藞忙l蕦n/",
  "geometry": "/d蕭i藞蓱m蕦tri/",
  "geothermal park": "/d蕭藢io蕣胃藞蓾m蕦l p藞蓱rk/",
  "getaway": "/伞藞蓻t蕦w藢e瑟/",
  "geyser": "/伞藞a瑟z蓾/",
  "ghana": "/伞藞忙n蕦/",
  "gladys claffern": "/伞l藞忙d瑟s/",
  "golf": "/伞藞蓱lf/",
  "grand": "/伞r藞忙nd/",
  "grant": "/伞r藞忙nt/",
  "graphic": "/伞r藞忙f瑟k/",
  "greedy": "/伞r藞idi/",
  "grill": "/伞r藞瑟l/",
  "grip": "/伞r藞瑟p/",
  "guilty": "/伞藞瑟lti/",
  "handkerchief": "/h藞忙艐k蓾t蕛瑟f/",
  "handshake": "/h藞忙nd蕛藢e瑟k/",
  "handwriting": "/h藞忙ndr藢a瑟t瑟艐/",
  "hatch": "/h藞忙t蕛/",
  "have an urge to": "/h藞忙v 藞忙n 藞蓾d蕭 t藞u/",
  "hazy": "/h藞e瑟zi/",
  "head start": "/h藞蓻d st藞蓱rt/",
  "herb": "/藞蓾b/",
  "hollow": "/h藞蓱lo蕣/",
  "horn": "/h藞蓴rn/",
  "housing": "/h藞a蕣z瑟艐/",
  "hugo award": "/hj藞u伞o蕣 蓹藞w蓴rd/",
  "hut": "/h藞蕦t/",
  "hydrogen": "/h藞a瑟dr蕦d蕭蕦n/",
  "hypothetical": "/h藢a瑟p蕦胃藞蓻t蕦k蕦l/",
  "iconic": "/藢a瑟k藞蓱n瑟k/",
  "in a league of one鈥檚 own": "/瑟n 蕦 l藞i伞 藞蕦v w藞蕦nz 藞o蕣n/",
  "in hand": "/瑟n h藞忙nd/",
  "inaction": "/藢瑟n藞忙k蕛蕦n/",
  "inch": "/藞瑟nt蕛/",
  "input": "/藞瑟np藢蕣t/",
  "integrity": "/藢瑟nt藞蓻伞r蕦ti/",
  "intermediate": "/藢瑟nt蓾m藞idi瑟t/",
  "isaac asimov": "/藞a瑟z蕦k 藞忙s瑟m蓱v/",
  "jam": "/d蕭藞忙m/",
  "jar": "/d蕭藞蓱r/",
  "jaw": "/d蕭藞蓴/",
  "joint": "/d蕭藞蓴瑟nt/",
  "jolt": "/d蕭藞o蕣lt/",
  "justice": "/d蕭藞蕦st蕦s/",
  "kayaking": "/k藞a瑟藢忙k瑟艐/",
  "kettle": "/k藞蓻t蕦l/",
  "kiwi": "/k藞iwi/",
  "knit": "/n藞瑟t/",
  "labour": "/l藞e瑟b蓾/",
  "ladder": "/l藞忙d蓾/",
  "lamp": "/l藞忙mp/",
  "laptop": "/l藞忙pt藢蓱p/",
  "larry belmont": "/l藞蓻ri b藞蓻lm藢蓱nt/",
  "lately": "/l藞e瑟tli/",
  "lawyer": "/l藞蓴j蓾/",
  "league": "/l藞i伞/",
  "leather": "/l藞蓻冒蓾/",
  "leftover": "/l藞蓻ft藢o蕣v蓾/",
  "lever": "/l藞蓻v蓾/",
  "liberty": "/l藞瑟b蓾t藢i/",
  "license": "/l藞a瑟s蕦ns/",
  "licensed": "/l藞a瑟s蕦nst/",
  "located": "/l藞o蕣k藢e瑟t蕦d/",
  "log": "/l藞蓴伞/",
  "mail": "/m藞e瑟l/",
  "mammal": "/m藞忙m蕦l/",
  "manned": "/m藞忙nd/",
  "manuka honey": "/藞h蕦ni/",
  "marco polo": "/m藞蓱rko蕣 p藞o蕣lo蕣/",
  "marie curie": "/m蓾藞i kj蕣r藞i/",
  "marine": "/m蓾藞in/",
  "maritime": "/m藞蓻r蕦t藢a瑟m/",
  "maximum": "/m藞忙ks蕦m蕦m/",
  "meanwhile": "/m藞inw藢a瑟l/",
  "merchant": "/m藞蓾t蕛蕦nt/",
  "mercy": "/m藞蓾si/",
  "migration": "/ma瑟伞r藞e瑟蕛蕦n/",
  "minister": "/m藞瑟n蕦st蓾/",
  "mixture": "/m藞瑟kst蕛蓾/",
  "monument": "/m藞蓱njum蕦nt/",
  "more like": "/m藞蓴r l藞a瑟k/",
  "mud": "/m藞蕦d/",
  "murder": "/m藞蓾d蓾/",
  "nail": "/n藞e瑟l/",
  "negotiate": "/n蕦伞藞o蕣蕛i藢e瑟t/",
  "nest": "/n藞蓻st/",
  "niece": "/n藞is/",
  "not to mention": "/n藞蓱t t藞u m藞蓻n蕛蕦n/",
  "olivia": "/o蕣l藞瑟vi蕦/",
  "on a 鈥?basis": "/藞蓱n 蕦 藞be瑟s蓹s/",
  "opponent": "/蕦p藞o蕣n蕦nt/",
  "orient": "/藞蓴ri藢蓻nt/",
  "overstatement": "/藞o蕣v蓾st藢e瑟tm蕦nt/",
  "pace": "/p藞e瑟s/",
  "pan": "/p藞忙n/",
  "panama": "/p藞忙n蕦m藢蓱/",
  "panel": "/p藞忙n蕦l/",
  "papua new guinea": "/p藞忙pju蕦 n藞u 伞藞瑟ni/",
  "parcel": "/p藞蓱rs蕦l/",
  "parking": "/p藞蓱rk瑟艐/",
  "participant": "/p蓱rt藞瑟s蕦p蕦nt/",
  "peak season": "/p藞ik s藞iz蕦n/",
  "pets (public english test system)": "/p藞蓻ts/",
  "phase": "/f藞e瑟z/",
  "pitch": "/p藞瑟t蕛/",
  "platform": "/pl藞忙tf藢蓴rm/",
  "plug": "/pl藞蕦伞/",
  "political": "/p蕦l藞瑟t蕦k蕦l/",
  "politics": "/p藞蓱l蕦t藢瑟ks/",
  "possession": "/p蕦z藞蓻蕛蕦n/",
  "pouch": "/p藞a蕣t蕛/",
  "pray": "/pr藞e瑟/",
  "pray that": "/pr藞e瑟 冒藞忙t/",
  "premier": "/pr蓻m藞瑟r/",
  "press conference": "/藞pr蓻s 藞k蓱nf蓺蓹ns/",
  "presume": "/pr瑟z藞um/",
  "prime minister": "/pr藞a瑟m m藞瑟n蕦st蓾/",
  "priority": "/pra瑟藞蓴r蕦ti/",
  "prison": "/pr藞瑟z蕦n/",
  "privilege": "/pr藞瑟vl蕦d蕭/",
  "profession": "/pr蕦f藞蓻蕛蕦n/",
  "proficiency": "/pr蕦f藞瑟蕛蕦nsi/",
  "profile": "/pr藞o蕣f藢a瑟l/",
  "pros and cons": "/pr藞o蕣z 蕦nd k藞蓱nz/",
  "puff": "/p藞蕦f/",
  "purse": "/p藞蓾s/",
  "radium": "/r藞e瑟di蕦m/",
  "random": "/r藞忙nd蕦m/",
  "receipt": "/r瑟s藞it/",
  "receptionist": "/r瑟s藞蓻p蕛蕦n瑟st/",
  "relay": "/r藞il藢e瑟/",
  "relay to": "/r藞il藢e瑟 t藞u/",
  "resign": "/r瑟z藞a瑟n/",
  "ridiculous": "/r瑟d藞瑟kj蕦l蕦s/",
  "rigid": "/r藞瑟d蕭蕦d/",
  "ripe": "/r藞a瑟p/",
  "robin lee graham": "/r藞蓱b蕦n l藞i 伞r藞e瑟蕦m/",
  "royal": "/r藞蓴瑟蕦l/",
  "rubber": "/r藞蕦b蓾/",
  "rumour": "/r藞um蓾/",
  "salary": "/s藞忙l蓾i/",
  "salesman": "/s藞e瑟lzm蕦n/",
  "saleswoman": "/s藞e瑟lzw藢蕣m蕦n/",
  "sample": "/s藞忙mp蕦l/",
  "saucer": "/s藞蓴s蓾/",
  "scenario": "/s瑟n藞蓻rio蕣/",
  "science fiction": "/s藞a瑟蕦ns f藞瑟k蕛蕦n/",
  "secondary": "/s藞蓻k蕦nd藢蓻ri/",
  "session": "/s藞蓻蕛蕦n/",
  "set sail": "/s藞蓻t 藞se瑟l/",
  "sew": "/s藞o蕣/",
  "shade": "/蕛藞e瑟d/",
  "slogan": "/sl藞o蕣伞蕦n/",
  "socialist": "/s藞o蕣蕛蕦l蕦st/",
  "spice": "/sp藞a瑟s/",
  "sponsor": "/sp藞蓱ns蓾/",
  "spy": "/sp藞a瑟/",
  "stability": "/st蕦b藞瑟l瑟ti/",
  "straightforward": "/str藞e瑟tf藞蓴rw蓾d/",
  "strait": "/str藞e瑟t/",
  "stun": "/st藞蕦n/",
  "submersible": "/s蕦bm藞蓾s瑟b蕦l/",
  "sulphuric pool": "/p藞ul/",
  "superior": "/sup藞瑟ri蓾/",
  "superior to": "/sup藞瑟ri蓾 t藞u/",
  "supervise": "/s藞up蓾v藢a瑟z/",
  "suspend": "/s蕦sp藞蓻nd/",
  "sydney": "/s藞瑟dni/",
  "tablet": "/t藞忙bl蕦t/",
  "take (鈥? for granted": "/t藞e瑟k f藞蓴r 伞r藞忙nt蕦d/",
  "take over": "/t藞e瑟k 藞o蕣v蓾/",
  "tale": "/t藞e瑟l/",
  "tasmania": "/t藢忙zm藞e瑟ni蕦/",
  "tasmanian devil": "/t藢忙zm藞e瑟ni蕦n d藞蓻v蕦l/",
  "tax": "/t藞忙ks/",
  "temporary": "/t藞蓻mp蓾藢蓻ri/",
  "test out": "/t藞蓻st 藞a蕣t/",
  "the bay of islands": "/冒蕦 b藞e瑟 藞蕦v 藞a瑟l蕦ndz/",
  "the communist manifesto": "/冒蕦 k藞蓱mj蕦n蕦st m藢忙n蕦f藞蓻st藢o蕣/",
  "the haka": "/冒蕦/",
  "the three-body problem": "/冒蕦 胃r藞i b藞蓱di pr藞蓱bl蕦m/",
  "tournament": "/t藞蕣rn蕦m蕦nt/",
  "trunk": "/tr藞蕦艐k/",
  "tube": "/t藞ub/",
  "tune": "/t藞un/",
  "turn out": "/t藞蓾n 藞a蕣t/",
  "underwater": "/藞蕦nd蓾w藢蓴t蓾/",
  "uniform": "/j藞un蕦f藢蓴rm/",
  "urge": "/藞蓾d蕭/",
  "venue": "/v藞蓻nju/",
  "vibrate": "/v藞a瑟bre瑟t/",
  "violence": "/v藞a瑟蕦l蕦ns/",
  "violent": "/v藞a瑟蕦l蕦nt/",
  "washroom": "/w藞蓱蕛r藢um/",
  "weed": "/w藞id/",
  "weekly": "/w藞ikli/",
  "whereas": "/w蓻r藞忙z/",
  "withdraw": "/w瑟冒dr藞蓴/",
  "withdraw from": "/w瑟冒dr藞蓴 fr藞蕦m/",
  "wool": "/w藞蕣l/",
  "wrinkle": "/r藞瑟艐k蕦l/",
  "wrist": "/r藞瑟st/",
  "zac sunderland": "/s藞蕦nd蓾l蕦nd/"
};

